# Generated by Django 2.2.5 on 2020-02-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content_html'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
