# Generated by Django 2.2.6 on 2019-11-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='satus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='satus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='satus',
            new_name='status',
        ),
    ]
