# Generated by Django 3.0.4 on 2020-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200313_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(default='', max_length=2020, verbose_name='标签描述'),
        ),
    ]
